title: Martin Brennan
email: mjrbrennan@gmail.com
description: >
  I’m Martin Brennan, and I’m a full stack staff software engineer based in Australia,
  currently working for [Discourse](https://discourse.org). I primarily enjoy working with Ruby,
  Rails, and JavaScript, with a focus on product engineering. I’m always seeking ways to expand
  my knowledge and learn about new tools, languages and frameworks.
baseurl: ""
url: "http://www.martin-brennan.com"
github_username: martin-brennan
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
twitter:
  username: mjrbrennan
author: mjrbrennan
comments: true
excerpt_separator: <!--more-->
paginate: 10
future: true
redirects: yes
