title: Martin Brennan
email: mjrbrennan@gmail.com
description: >
  I’m Martin Brennan, and I’m a full stack software engineer based in Australia.
  I primarily enjoy working with Ruby, Rails, C#, and JavaScript but I’m always seeking ways
  to expand my knowledge and learn about new tools, languages and frameworks.
baseurl: ""
url: "http://www.martin-brennan.com"
twitter_username: mjrbrennan
github_username: martin-brennan
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
twitter:
  username: mjrbrennan
author: mjrbrennan
comments: true
excerpt_separator: <!--more-->
paginate: 10
future: true
redirects: yes
